### ISSUE TITLE
[Bug] 無法正常還原覆蓋多行的操作

### ISSUE THREAD

**Issue by ghost** [Quadrats/quadrats#20]
**Problems**
選取多行的情況下輸入任意鍵取代後, 按下 Cmd + Z undo 會多還原一次操作
問題至少存在於 v0.1.0 之前
![Examples _ Playgroud - All ⋅ Storybook](https://user-images.githubusercontent.com/83571075/155133413-3440aa83-345b-4636-bece-16b06c38b4c7.gif)

**expected behavior**
Cmd+Z undo 後應還原為操作前的資料

**Steps to Reproduce**
1. 在空白的 Quadrats 元件內輸入 1
2. 按下 Enter 換行
3. 在新行輸入 2
4. 按下 Enter 換行
5. 一次框選 1 與 2 兩行
6. 輸入 3 取代框選的兩行
7. 按下 undo 的快速鍵 (Cmd + Z)
8. 操作被還原兩次, 第二行沒有 2

**Comment by fantasywind** [comment]
look fixed
