### ISSUE TITLE
facebook embed

### ISSUE THREAD

**Issue by ting-ting-ting** [Quadrats/quadrats#25]
- https://www.facebook.com/100064725244964/posts/689388036562032/?mibextid=7eNqk6

- [https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fichef[…]mqySWNZCnjswd2Kh5WxYKsBM8YanJZHKpSl&show_text=true&width=500](https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fichefpos.taiwan%2Fposts%2Fpfbid0UpivhGsDAeBv4FFm3kTkQ3jSHYv1VemqySWNZCnjswd2Kh5WxYKsBM8YanJZHKpSl&show_text=true&width=500)

這兩種形式的連結無法遷入

**Comment by fantasywind** [comment]
研究了一下，因為不是完整 iframe 格式沒有辦法知道正確的長寬比例，因此只接受 iframe 格式
