### ISSUE TITLE
footnote 打中文時原本的字會被取代

### ISSUE THREAD

**Issue by ting-ting-ting** [Quadrats/quadrats#27]
![截圖 2023-11-13 下午4 02 43](https://github.com/Quadrats/quadrats/assets/71868179/f49f6185-9120-4462-b58f-06d90fe4d35a)
![截圖 2023-11-13 下午4 02 52](https://github.com/Quadrats/quadrats/assets/71868179/4a69bc22-c905-4e1f-817a-a6e74a70a63c)

EX: 
把很美麗反白＋上註腳，打上棒棒
原本的很美麗就變成棒棒了

**Comment by fantasywind** [comment]
resolved on 77c6f49
